### ISSUE TITLE
Does Remote XUL Manager works with/compatible with latest SeaMonkey 2.4.6

### ISSUE THREAD

**Issue by rajneesh75** [jvillalobos/Remote-XUL-Manager#22] opened 2017-01-03 17:46 UTC
Hi 

I have been trying to work Remote XUL Manager with SeaMonkey browser. It installs fine and I am able to add whitelists. But when I close SeaMonkey and restart, SeaMonkey crashes and sends a crash report to Mozilla. This doesn't happen in old versions though.

Thanks
Rajneesh Sharma

**Comment by jvillalobos** [comment] 2017-01-03 17:48
It should work in the same way as it does in Firefox. However, I haven't tested the add-on on SeaMonkey for a very long time.  Does disabling the add-on fix the crashing problem? Can you consistently reproduce the crash?

**Comment by rajneesh75** [comment] 2017-01-03 18:15
Yes, I think so that remote xul manager is causing it, though I am still doing more tests. I don't have any other add on installed. Also take a look at crash report. I will do more tests and let you know if I think its not a remote xul manager issue.

Add-ons: %7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:2.46,remotexulmanager%40xulforge.com:1.3.2
AvailablePageFile: 4698300416
AvailablePhysicalMemory: 1449320448
AvailableVirtualMemory: 4041711616
BIOS_Manufacturer: Hewlett-Packard
BlockedDllList: 
BreakpadReserveAddress: 105971712
BreakpadReserveSize: 67108864
BuildID: 20161213183751
CrashTime: 1483467179
EMCheckCompatibility: true
Email: rajneesh75@yahoo.com
FramePoisonBase: 00000000f0de0000
FramePoisonSize: 65536
InstallTime: 1483467127
ProductID: {92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}
ProductName: SeaMonkey
ReleaseChannel: release
SafeMode: 0
StartupTime: 1483467178
SystemMemoryUsePercentage: 65
Theme: classic/1.0
Throttleable: 1
TotalPageFile: 8372244480
TotalPhysicalMemory: 4187074560
TotalVirtualMemory: 4294836224
URL: 
UptimeTS: 3.950758006
Vendor: Mozilla
Version: 2.46
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by rajneesh75** [comment] 2017-01-03 18:35
It happened with an old version also

AdapterDeviceID: 0x0a16
AdapterDriverVersion: 9.18.10.3324
AdapterSubsysID: 198f103c
AdapterVendorID: 0x8086
Add-ons: %7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:2.40,remotexulmanager%40xulforge.com:1.3.2
AvailablePageFile: 5247528960
AvailablePhysicalMemory: 1979002880
AvailableVirtualMemory: 3996303360
BIOS_Manufacturer: Hewlett-Packard
BlockedDllList: 
BreakpadReserveAddress: 47185920
BreakpadReserveSize: 67108864
BuildID: 20160120202951
CrashTime: 1483468402
EMCheckCompatibility: true
Email: rajneesh75@yahoo.com
FramePoisonBase: 00000000f0de0000
FramePoisonSize: 65536
InstallTime: 1483467449
Notes: AdapterVendorID: 0x8086, AdapterDeviceID: 0x0a16, AdapterSubsysID: 198f103c, AdapterDriverVersion: 9.18.10.3324
DWrite? DWrite+ D2D1.1? D2D1.1+ D2D? D2D1.1V? D2D1.1V+ D2D+ 
ProductID: {92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}
ProductName: SeaMonkey
ReleaseChannel: release
SafeMode: 0
StartupTime: 1483468401
SystemMemoryUsePercentage: 52
Theme: classic/1.0
Throttleable: 1
TotalPageFile: 8372244480
TotalPhysicalMemory: 4187074560
TotalVirtualMemory: 4294836224
URL: 
Vendor: Mozilla
Version: 2.40
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by jvillalobos** [comment] 2020-05-04 20:35
This extension is no longer maintained, since Firefox moved to a different extensions platform. Closing.

**Closed by jvillalobos** 2020-05-04 20:35 UTC
